services:
  - type: web
    name: intersection-noisecraft
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production

