services:
  - type: web
    name: intersection-realtime
    env: node
    plan: free
    rootDir: realtime
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

